### ISSUE TITLE
Inicio de sesión para la compra

### ISSUE THREAD

**Issue by Arcila24** [JuanPinillo/proyecto-tienda-deportiva-deporte-total#16]
Necesitamos que nuestro modulo de Promociones deje comprar a el usuario pero solamente si inicia sesión de lo contrario lo haga registrar a nuestra pagina y ahí si lo deje comprar algún producto y le permita cerrar sesión. @JuanPinillo

**Comment by JuanPinillo** [comment]
En progreso

**Comment by JuanPinillo** [comment]
tarea terminada con exito
